- README.md
- internal/config/config_format.go
- internal/config/presets.go
- internal/handlers/juju.go
- internal/providers/lxd.go
- internal/providers/microk8s.go
- internal/providers/providers.go
- internal/runner/runner.go
- tests/juju-model-defaults/concierge.yaml
- tests/preset-k8s-pack-charm/task.yaml
- tests/preset-k8s/task.yaml
- tests/provider-lxd/concierge.yaml
- tests/provider-microk8s/concierge.yaml
This PR implements a new `bootstrap` option for providers.
This is because in some cases, it's desirable to have a provider
installed, but not bootstrapped with a Juju controller.
The most clear example of this is when building a K8s charm, LXD
is still required to build the charm with charmcraft.
> Explicit provider bootstrap

- README.md
- cmd/main.go
- cmd/prepare.go
- cmd/restore.go
- internal/concierge/manager.go
- internal/handlers/deb.go
- internal/handlers/juju.go
- internal/handlers/snap.go
- internal/packages/snap.go
- internal/packages/snap_test.go
- internal/providers/lxd.go
- internal/providers/microk8s.go
- internal/runner/command.go
- internal/runner/runner_test.go
- internal/runner/user.go
Before this commit, nearly all commands were run using `sudo`.
This was making the assumption that the user executing the
command was able to escalate using `sudo` with no password.
There was no handling in `concierge` to enable a password prompt,
so if the relevant configuration was not in place for NOPASSWD
sudo, then `concierge` would hang.
Additionally, by not being able to gurantee root privileges,
`concierge` was unable to take full advantage of the native
`snapd` client package for installing multiple snaps.
> feat!: require `concierge` to be run as `root`

- README.md
- cmd/prepare.go
- internal/concierge/plan.go
- internal/config/config.go
- internal/config/config_format.go
- internal/config/overrides.go
- internal/juju/juju.go
- internal/juju/juju_test.go
- internal/packages/deb_handler.go
- internal/packages/deb_handler_test.go
- internal/packages/snap_handler.go
- internal/packages/snap_handler_test.go
- internal/providers/google.go
- internal/providers/google_test.go
- internal/providers/lxd.go
- internal/providers/lxd_test.go
- internal/providers/microk8s.go
- internal/providers/microk8s_test.go
- internal/providers/providers.go
- internal/runner/command.go
- internal/runner/interface.go
- internal/runner/runner.go
- internal/runnertest/mock_runner.go
- internal/runnertest/mock_snap.go
- tests/provider-google/concierge.yaml
- tests/provider-google/credentials.yaml
- tests/provider-google/task.yaml
Early ground work for supporting providers for which credentials need to be provided.
First target is Google, but more will be easy to add.
Example config:
```yaml
juju:
channel: 3.5/stable
model-defaults:
test-mode: "true"
automatically-retry-hooks: "false"
providers:
google:
enable: true
bootstrap: true
credentials-file: /home/ubuntu/data/temp/google.yaml
```
Example output:
```
ubuntu@ubuntu-noble-2e39:~/data/code/canonical/concierge$ sudo go run . prepare -v --trace
time=2024-10-18T14:03:42.240Z level=INFO msg="Configuration file found" path=concierge.yaml
time=2024-10-18T14:03:42.240Z level=DEBUG msg="Filesystem ownership changed" user=ubuntu group=1000 path=/home/ubuntu/.cache
time=2024-10-18T14:03:42.240Z level=DEBUG msg="Filesystem ownership changed" user=ubuntu group=1000 …
```
> wip: add a google provider

- README.md
- internal/concierge/plan.go
- internal/concierge/plan_validators.go
- internal/concierge/plan_validators_test.go
- internal/config/config_format.go
- internal/config/overrides.go
- internal/providers/canonical-k8s.go
- internal/providers/canonical-k8s_test.go
- internal/providers/providers.go
- tests/provider-canonical-k8s/concierge.yaml
- tests/provider-canonical-k8s/task.yaml
This PR implements support for Canonical K8s as a provider, as the successor to MicroK8s.
> feat: add Canonical K8s provider

- .gitignore
- spread.yaml
- tests/cloud-config.yaml
Simple change to avoid using a hard-coded password for the `spread` workers.
> test: use ephemeral ssh passwords for spread

- README.md
- internal/providers/k8s.go
- internal/providers/k8s_test.go
- tests/provider-k8s/concierge.yaml
- tests/provider-k8s/task.yaml
concierge by default attempts to install the k8s snap at 1.31/candidate, but no such release exists:
changed all defaults to install 1.31-classic instead.
> fix: change default channel for k8s snap to 1.31-classic

- internal/system/runner.go
This proposed change generates a trace of a failing command automatically, even if tracing is disabled.
This would be useful when running in CI. Recently, I have seen `concierge` fail to install LXD with this simple log line:
```
time=2024-11-18T20:55:23.847Z level=ERROR msg="Failed to configure machine" error="failed to install LXD: failed to install snap: command failed: exit status 1"
```
The error does not happen consistently, and the error message in that case is not useful.
> fix: Log command output on failure

- internal/config/presets.go
- internal/providers/k8s_test.go
Follow up to #17.
Previously, if K8s was already installed but not configured with the `network` feature enabled, the `concierge` presets would not enable the `network` feature explicitly - causing the load balancer configuration to fail.
This change ensures that for the *presets* using k8s, `network` is explicitly enabled.
> fix: ensure `network` is enabled for k8s presets

- internal/providers/lxd.go
- internal/providers/lxd_test.go
Testing - it seems that #21 may have stopped the `prepare` phase from succeeding because LXD is no longer running, and cannot initialise.
> fix: ensure that `lxd` is started again after refresh

- README.md
- cmd/main.go
- cmd/root.go
- cmd/status.go
- internal/concierge/manager.go
- internal/config/config_format.go
- tests/status-failed/concierge.yaml
- tests/status-failed/task.yaml
- tests/status-success/concierge.yaml
- tests/status-success/task.yaml
Adds a command that can be used to check whether or not concierge has succeeded, failed or is in progress on a machine.
Fixes #31
> feat: add `concierge status` command.

- internal/system/snap.go
This is a simple fix that ensures that non-existent snaps don't get repeatedly looked up with the retry mechanism used to establish more detailed Snap information.
The primary motivation for this is failing fast rather than keeping the user waiting if they specify a non-existent snap.
> fix: lookup snap in store and bail early if not exists in SnapInfo

- README.md
- cmd/prepare.go
- internal/concierge/plan.go
- internal/config/config.go
- internal/config/config_format.go
- internal/config/overrides.go
- internal/config/presets.go
- tests/disable-juju-config/concierge.yaml
- tests/disable-juju-config/task.yaml
- tests/disable-juju-env-var/task.yaml
- tests/disable-juju-flag/task.yaml
- tests/preset-crafts/task.yaml
This PR adds to option for Juju to be *explicitly disabled* as part of the provisioning.
Concierge was initially imagined as a tool to build test environments for charms, and as such I think it's default should be to make Juju available.
That said there are examples of situations where `concierge` is useful, but Juju is not required. #27 is one such example of that, but there may be other situations where using `concierge` to provision Canonical K8s in CI is desirable, but Juju is not required.
Contrary to the providers, which have an `Enable` option, this PR introduces `Juju.Disable` so as to make it explicit to *opt out* of Juju, rather than make Juju opt in.
tl;dr `concierge prepare -p k8s --disable-juju` or similar.
Drive by to add a `crafts` preset which fixes #27, given that the …
> feat: ability to disable juju install/bootstrap entirely

- .gitignore
- README.md
- internal/system/runner.go
Adding this so it's a bit easier to see what commands take the most time (maybe in future we can speed up some things).
Change "Running" to "Starting", mainly so it's the same width as "Finished" and these logs come out aligned nicely like so:
```
time=2025-03-06T17:17:28.505+13:00 level=DEBUG msg="Starting command" command="/usr/bin/sleep 1.23" 
time=2025-03-06T17:17:29.738+13:00 level=DEBUG msg="Finished command" command="/usr/bin/sleep 1.23" elapsed=1.232700868s
```
Also tweak a couple of other things:
- Add .idea to .gitignore for GoLand IDE
- Simplify "go build" and "go run" commands in README.md (these args are implied)
> feat: show time taken to run each command in --verbose mode

- internal/juju/juju.go
- internal/juju/juju_test.go
Testing if the output contains just "not found" is too loose, as some intermittent errors include phrases like "pod not found", for example:
```
Command: /snap/bin/juju show-controller concierge-microk8s Output:
{}
ERROR opening API connection: starting proxy for api connection: \
connecting k8s proxy: forwarding ports: error upgrading connection: \
unable to upgrade connection: pod not found ("controller-0_controller-concierge-microk8s")
```
So look for the specific `controller <name> not found` error. This might be a bit *too* narrow, but at least it'll work.
This bug was causing concierge to think the controller wasn't there, and falling through to do the bootstrap, which then failed with "controller ... already exists" and kept retrying.
The PR branch is on my `benhoyt/concierge` …
> fix: look for more a specific error in checkBootstrapped

- go.mod
- internal/system/util.go
Per [discussion on mattermost](https://chat.canonical.com/canonical/pl/4qmqkitr6pys5dgeji6tqz7i6w), we need to fix https://github.com/advisories/GHSA-6f52-wpx2-hvf2 by upgrading to Go 1.24.4.
Similar to the Pebble repo, `snyk test` scan doesn't find this CVE in this repo:
```bash
$ snyk test
Testing /Users/tiexin/work/concierge...
Organization:      ironcore864
Package manager:   gomodules
Target file:       go.mod
Project name:      github.com/canonical/concierge
Open source:       no
Project path:      /Users/tiexin/work/concierge
Licenses:          enabled
✔ Tested 104 dependencies for known issues, no vulnerable paths found.
Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.
```
But to be on the safer side, we …
> chore: fix CVE-2025-22874

- .goreleaser.yaml
- internal/providers/microk8s.go
Similar to #81 (s390x), this PR adds goreleaser for the ppc64le architecture.
> build: release snap for ppc64le arch

- .github/workflows/tiobe.yaml
Our TIOBE contact let us know we need to update the staticcheck tool they use to support Go 1.24.
> chore: update TIOBE staticcheck dependency

- .github/workflows/tiobe.yaml
We've been asked to [run the TIOBE workflow weekly](https://discourse.canonical.com/t/tiobe-tics-news-maas-ui-go-1-24-ci-integration-tics-gh-self-hosted-runner/6038?u=tony-meyer). This changes from monthly on the first of the month to weekly on Sundays.
> chore: run TIOBE weekly

- .github/dependabot.yml
Avoid dependabot creating language labels (particularly in this case "go") so that we have consistent labels across Charm Tech repositories.
> ci: limit labels from dependabot

- README.md
- internal/config/config_format.go
- internal/juju/juju.go
- internal/juju/juju_test.go
Adds a new config option in `juju`, `agent-version`. When specified, this is passed as `--agent-version` when bootstrapping Juju.
This is particularly useful when there is an issue with the latest agent version and users want to restrict the agent version to one without the issue, but otherwise use the latest Juju.
> feat: add an option to pass --agent-version when bootstrapping
